# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         Finance-TickerSymbols
version:      0.01
version_from: lib/Finance/TickerSymbols.pm
installdirs:  site
requires:
    LWP::Simple:                   1

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.30
